### ISSUE TITLE
Intake

### ISSUE THREAD

**Issue by randomplz** [pinapelz/1010MTowerTakeover#5]
Intake is spinning on its own

**Comment by pinapelz** [comment]
Can you Elaborate on this issue? Is this happening the moment you start the program or is it only when you press a button

**Comment by pinapelz** [comment]
**A Patch for this issue has been attempted. Please download Heritage Woods 2020 Code (Just try one of them)**

**Comment by randomplz** [comment]
To be specific, when I click the intake button, the left intake start spinning on its own even after when the program is closed

**Comment by pinapelz** [comment]
Solved in the last upload
